import { Product } from './types.ts';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Sập gụ tủ chè (Khảm trai)',
    category: 'Đồ gỗ lối cổ',
    unitPrice: 45000000,
    costPrice: 32000000,
    unit: 'each',
    stock: 2,
    description: 'Chất liệu gỗ gụ cũ, khảm trai ốc xà cừ tinh xảo',
  },
  {
    id: '2',
    name: 'Bàn ghế Trường kỷ (Tam sơn)',
    category: 'Bàn ghế',
    unitPrice: 32000000,
    costPrice: 22000000,
    unit: 'each',
    stock: 3,
    description: 'Bộ 3 món, gỗ trắc hoặc gỗ cẩm, mộng thủ công',
  },
  {
    id: '3',
    name: 'Tranh gỗ tứ quý',
    category: 'Decor cổ',
    unitPrice: 12000000,
    costPrice: 8000000,
    unit: 'each',
    stock: 5,
    description: 'Tùng - Trúc - Cúc - Mai, gỗ hương đỏ đục tay',
  },
  {
    id: '4',
    name: 'Tủ bày đồ (Lối Tàu)',
    category: 'Tủ trưng bày',
    unitPrice: 15500000,
    costPrice: 11000000,
    unit: 'each',
    stock: 4,
    description: 'Gỗ gụ mật, phong cách cổ điển, đánh vecni thủ công',
  },
  {
    id: '5',
    name: 'Cuốn thư câu đối',
    category: 'Đồ thờ',
    unitPrice: 8500000,
    costPrice: 6000000,
    unit: 'm',
    stock: 10,
    description: 'Sơn son thếp vàng, tính theo mét dài thực tế',
  },
  {
    id: '6',
    name: 'Vách CNC gỗ tự nhiên',
    category: 'Nội thất rời',
    unitPrice: 2800000,
    costPrice: 1900000,
    unit: 'm2',
    stock: 25,
    description: 'Họa tiết triện cổ, gỗ gõ đỏ',
  },
];
